- name: Print Scylla node variables
  hosts: scylla
  gather_facts: yes
  vars:
    scylla_nic: "eth0"
  tasks:
    - name: Set Scylla addresses
      set_fact:
        scylla_listen_address: "{{ vars['ansible_' ~ scylla_nic].ipv4.address }}"
        scylla_rpc_address: "{{ vars['ansible_' ~ scylla_nic].ipv4.address }}"
        scylla_broadcast_address: "{{ vars['ansible_' ~ scylla_nic].ipv4.address }}"

    - name: Print Scylla addresses
      debug:
        msg:
          - "Listen address: {{ scylla_listen_address }}"
          - "RPC address: {{ scylla_rpc_address }}"
          - "Broadcast address: {{ scylla_broadcast_address }}"
          - "Data Center: {{ dc }}"
          - "Rack: {{ rack }}"
  roles:
    - scylla-ansible-roles/ansible-scylla-node