- name: Deploy Enterprise ScyllaDB Cluster
  hosts: scylla
  become: true
  vars:
    scylla_raid_setup:
      - /dev/nvme0n1
    scylla_dependencies:
      - curl
      - wget
    scylla_version: latest
    scylla_edition: enterprise
    scylla_cluster_name: 'testcluster'
    scylla_snitch: GossipingPropertyFileSnitch
    adjust_audit_replication: 'false'
    adjust_system_auth_replication: 'true'
    adjust_system_distributed_replication: 'true'
    adjust_system_traces_replication: 'true'
    cpuset_command: scylla_cpuset_setup --cpuset 0-1
    elrepo_kernel: 'false'
    full_inventory: 'true'
    gpfs_prefer_local: 'true'
    install_only: 'false'
    install_type: online
    io_conf: SEASTAR_IO="--io-properties-file=/etc/scylla.d/io_properties.yaml"
    reboot_after_kernel_upgrade: 'true'
    scylla_authentication: 'false'
    scylla_bootstrap_wait_time_sec: '25200'
    scylla_broadcast_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_io_probe: 'true' 
    scylla_listen_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_manager_agent_upgrade: 'false'
    scylla_nic: '{{ ansible_default_ipv4.interface }}'
    scylla_rpc_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_ssl:
        cert_path: /etc/scylla/
        client:
            enabled: false
        internode:
            enabled: false
            internode_encryption: all
    scylla_yaml_params:
        compaction_enforce_min_threshold: true
        compaction_static_shares: 100
        components_memory_reclaim_threshold: 1.0
        consistent_cluster_management: true
        force_schema_commit_log: true
        hinted_handoff_enabled: false
        internode_compression: all
        max_clustering_key_restrictions_per_query: 1000
        max_memory_for_unlimited_query: 104857600
        max_partition_key_restrictions_per_query: 1000
    skip_installed_scylla_version_check: 'false'
    start_scylla_service: 'true'
    swap_file_size_mb: '1024'
    sysctl:
    - name: vm.swappiness
      value: '10'
    - name: vm.dirty_ratio
      value: '60'
    - name: vm.dirty_background_ratio
      value: '2'
    - name: net.ipv4.tcp_synack_retries
      value: '2'
    - name: net.ipv4.ip_local_port_range
      value: 2000 65535
    - name: net.ipv4.tcp_rfc1337
      value: '1'
    - name: net.ipv4.tcp_fin_timeout
      value: '15'
    - name: net.ipv4.tcp_keepalive_time
      value: '300'
    - name: net.ipv4.tcp_keepalive_probes
      value: '5'
    - name: net.ipv4.tcp_keepalive_intvl
      value: '15'
    - name: net.core.rmem_default
      value: '31457280'
    - name: net.core.rmem_max
      value: '12582912'
    - name: net.core.wmem_default
      value: '31457280'
    - name: net.core.wmem_max
      value: '12582912'
    - name: net.core.somaxconn
      value: '65535'
    - name: net.core.netdev_max_backlog
      value: '65535'
    - name: net.core.optmem_max
      value: '25165824'
    - name: net.ipv4.tcp_mem
      value: 65535 131072 262144
    - name: net.ipv4.udp_mem
      value: 65535 131072 262144
    - name: net.ipv4.tcp_rmem
      value: 8192 87380 16777216
    - name: net.ipv4.udp_rmem_min
      value: '16384'
    - name: net.ipv4.tcp_wmem
      value: 8192 65535 16777216
    - name: net.ipv4.udp_wmem_min
      value: '16384'
    - name: net.ipv4.tcp_max_tw_buckets
      value: '1440000'
    - name: net.ipv4.tcp_tw_reuse
      value: '1'
    - name: fs.nr_open
      value: '1073741816'
    - name: fs.file-max
      value: '9223372036854775807'
    update_sysctl: 'true'
    scylla_seeds:
      - "{{ groups['scylla'][0] }}"
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'
    scylla_manager_enabled: false
    generate_monitoring_config: false
    scylla_manager_repo_url: 
  tasks:
    # Workaround for some Debian versions that might not have XFS support out of the box
    - name: install XFSprogs
      package:
        name: xfsprogs
        state: present
      become: true
  roles:
    - scylla-ansible-roles/ansible-scylla-node