- name: Deploy Enterprise ScyllaDB Cluster
  hosts: scylla
  become: true

  vars:
    #mdadm_arrays:
    #- name: 'md0'
    #  devices:
    #    - '/dev/nvme0n1'
    #    - '/dev/nvme1n1'
    #  filesystem: 'xfs'
    #  level: '0'
    #  mountpoint: '/var/lib/scylla'
    #  state: 'present'
    #  opts: 'noatime,nofail'
    scylla_dependencies:
      - curl
      - wget
    scylla_version: latest
    scylla_edition: enterprise
    scylla_cluster_name: 'testcluster'
    scylla_snitch: GossipingPropertyFileSnitch
    scylla_io_probe: True
    enable_mc_format: true
    scylla_seeds:
      - "{{ groups['scylla'][0] }}"
      - "{{ groups['scylla'][1] }}"
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'
    scylla_broadcast_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_rpc_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_listen_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    scylla_manager_enabled: true
    generate_monitoring_config: false
    scylla_manager_repo_url: 
  tasks:
    # Workaround for some Debian versions that might not have XFS support out of the box
    - name: install XFSprogs
      package:
        name: xfsprogs
        state: present
      become: true
  roles:
    - scylla-ansible-roles/ansible-scylla-node