- name: Deploy ScyllaDB Cluster
  hosts: scylla
  become: true
  vars:
    # ScyllaDB repository URL
    scylla_repos:
      - 'https://repositories.scylladb.com/scylla/repo/****/centos/scylladb-4.1.repo'

    # ScyllaDB dependencies
    scylla_dependencies:
      - curl
      - wget

    # ScyllaDB version and edition
    scylla_version: latest
    scylla_edition: oss

    # Cluster configuration
    scylla_cluster_name: 'democluster'
    scylla_snitch: GossipingPropertyFileSnitch
    scylla_io_probe: True
    enable_mc_format: true

    # Seed nodes for the cluster
    scylla_seeds:
      - "{{ groups['scylla'][3] }}"
      - "{{ groups['scylla'][4] }}"
      - "{{ groups['scylla'][5] }}"

    # API configuration
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'

    # Monitoring and manager configuration
    generate_monitoring_config: True
    scylla_manager_enabled: true
    scylla_manager_repo_url: "https://downloads.scylladb.com/rpm/centos/scylladb-manager-2.1.repo"

  roles:
    - ansible-scylla-node
