- name: Deploy Enterprise ScyllaDB Cluster
  hosts: scylla
  vars:
    scylla_raid_setup:
      - /dev/nvme0n1
    scylla_dependencies:
      - curl
      - wget
    scylla_version: latest
    scylla_edition: enterprise
    scylla_cluster_name: 'testcluster'
    scylla_snitch: GossipingPropertyFileSnitch
    elrepo_kernel: false
    full_inventory: true
    install_only: false
    install_type: online
    scylla_authentication: false
    scylla_ssl:
        cert_path: /etc/scylla/
        client:
            enabled: false
        internode:
            enabled: false
            internode_encryption: all
    scylla_yaml_params:
        force_schema_commit_log: true
        internode_compression: all
    start_scylla_service: 'true'
    swap_file_size_mb: '1024'
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'
    scylla_manager_enabled: false
    generate_monitoring_config: true
  roles:
    - scylla-ansible-roles/ansible-scylla-node