- name: Deploy Enterprise ScyllaDB Cluster
  hosts: scylla
  become: true
  vars:
    scylla_raid_setup:
      - /dev/nvme0n1
    scylla_dependencies:
      - curl
      - wget
    scylla_version: latest
    scylla_edition: enterprise
    scylla_cluster_name: 'testcluster'
    scylla_snitch: GossipingPropertyFileSnitch
    elrepo_kernel: false
    full_inventory: true
    install_only: false
    install_type: online
    scylla_authentication: false
    #scylla_manager_agent_upgrade: false
    #io_conf: SEASTAR_IO="--io-properties-file=/etc/scylla.d/io_properties.yaml"
    #scylla_bootstrap_wait_time_sec: '25200'
    #scylla_broadcast_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    #scylla_io_probe: true 
    #scylla_listen_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    #scylla_nic: '{{ ansible_default_ipv4.interface }}'
    #scylla_rpc_address: '{{ hostvars[inventory_hostname][''ansible_''~scylla_nic].ipv4.address }}'
    #scylla_ssl:
    #    cert_path: /etc/scylla/
    #    client:
    #        enabled: false
    #    internode:
    #        enabled: false
    #        internode_encryption: all
    scylla_yaml_params:
        force_schema_commit_log: true
        internode_compression: all
    start_scylla_service: 'true'
    swap_file_size_mb: '1024'
    # Only one Seed is required, more than this, the cluster can't start
    #scylla_seeds:
    #  - "{{ groups['scylla'][0] }}"
    scylla_api_address: '127.0.0.1'
    scylla_api_port: '10000'
    scylla_manager_enabled: false
    generate_monitoring_config: true
  # Path to the Scylla Ansible Role directory
  roles:
    - scylla-ansible-roles/ansible-scylla-node